apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-app
spec:
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: target
  ports:
  - port: 80
